"""mvp_agents_schema_phase_2

Revision ID: 54c3c445c9d4
Revises: 54d1d5566ba4
Create Date: 2026-03-07 23:16:31.448241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c3c445c9d4'
down_revision: Union[str, Sequence[str], None] = '54d1d5566ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
