"""step_a_mvp_schema_contracts

Revision ID: 54d1d5566ba4
Revises: b7cf93d4cfc5
Create Date: 2026-03-04 09:04:00.161151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d1d5566ba4'
down_revision: Union[str, Sequence[str], None] = 'b7cf93d4cfc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
