"""add users projects and generation project link

Revision ID: b7cf93d4cfc5
Revises: c5ce00361ea6
Create Date: 2026-03-03 22:20:45.722688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cf93d4cfc5'
down_revision: Union[str, Sequence[str], None] = 'c5ce00361ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_generations_project_id'), 'generations', ['project_id'], unique=False)
    op.create_foreign_key(None, 'generations', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generations', type_='foreignkey')
    op.drop_index(op.f('ix_generations_project_id'), table_name='generations')
    op.drop_column('generations', 'project_id')
    # ### end Alembic commands ###
