import json

from openai import OpenAI

from app.core.config import settings
from app.core.llm_tracker import tracked_responses


def _fallback_research(
    project_name: str,
    questionnaire_responses: list[dict],
    analysis_report: dict,
    business_address: str | None = None,
) -> dict:
    context_excerpt = " ".join(
        (r.get("answer_text") or "") for r in questionnaire_responses
    )[:1200]
    primary_segment = (
        analysis_report.get("segment_attractiveness_analysis", {}).get(
            "recommended_primary_segment", "Primary local customers"
        )
    )

    return {
        "project_name": project_name,
        "target_customer_insights": [
            {
                "theme": "Primary motivations",
                "insight": "Customers value reliability, convenience, and outcome quality.",
            },
            {
                "theme": "Decision barriers",
                "insight": "Price sensitivity and trust in provider consistency can delay purchase.",
            },
            {
                "theme": "Information behavior",
                "insight": "Customers compare options through social proof, online presence, and referrals.",
            },
        ],
        "competitor_insights": [
            {
                "theme": "Competitive intensity",
                "insight": "Competition appears moderate to high in common service categories.",
            },
            {
                "theme": "Market gaps",
                "insight": "Potential gap in premium personalization and fast-response support.",
            },
            {
                "theme": "Differentiation opportunity",
                "insight": f"Position around segment-specific value for {primary_segment}.",
            },
        ],
        "research_summary": (
            "Fallback research generated from internal questionnaire and analysis context. "
            "External source integration via MCP web_search is pending."
        ),
        "business_address": business_address or "",
        "context_excerpt": context_excerpt,
        "sources": [
            {
                "title": "Internal Questionnaire Responses",
                "url": "internal://questionnaire",
                "note": "User-provided business and customer input.",
            },
            {
                "title": "Segment Attractiveness Analysis",
                "url": "internal://analysis",
                "note": "Generated by SegmentAnalystAgent.",
            },
        ],
        "reasoning": (
            f"Research generated from your questionnaire answers and market analysis for {project_name}. "
            f"Insights reflect the recommended primary segment ({primary_segment}) identified in your analysis."
        ),
    }


def generate_research_report(
    project_name: str,
    questionnaire_responses: list[dict],
    analysis_report: dict,
    business_address: str | None = None,
) -> dict:
    if not settings.can_use_openai():
        return _fallback_research(
            project_name,
            questionnaire_responses,
            analysis_report,
            business_address=business_address,
        )

    prompt = (
        "You are MarketResearchAgent for an AI-driven marketing tool.\n"
        "Create deeper target-customer and direct-competitor research using provided data.\n"
        "Return strict JSON with keys:\n"
        "project_name, target_customer_insights, competitor_insights, research_summary, sources, reasoning.\n"
        "Each item in target_customer_insights and competitor_insights must have: theme, insight.\n"
        "Include 3-6 items in each list.\n"
        "Include 2-6 sources with keys: title, url, note.\n"
        "If no external sources exist, use internal placeholder URLs prefixed with internal://.\n"
        'reasoning: 2-3 sentences citing which questionnaire answers and analysis data drove the research conclusions.\n\n'
        f"Project name:\n{project_name}\n\n"
        f"Business address/location:\n{business_address or ''}\n\n"
        f"Questionnaire responses:\n{json.dumps(questionnaire_responses, ensure_ascii=True)}\n\n"
        f"Analysis report:\n{json.dumps(analysis_report, ensure_ascii=True)}"
    )

    try:
        client = OpenAI(
            api_key=settings.openai_api_key,
            base_url=settings.openai_base_url,
            timeout=15,
            max_retries=0,
        )
        resp = tracked_responses(client, agent="market_researcher",
            model=settings.openai_model,
            input=prompt,
        )
        parsed = json.loads(resp.output_text.strip())
        required = {
            "project_name",
            "target_customer_insights",
            "competitor_insights",
            "research_summary",
            "sources",
        }
        if not required.issubset(parsed.keys()):
            return _fallback_research(
                project_name,
                questionnaire_responses,
                analysis_report,
                business_address=business_address,
            )
        return parsed
    except Exception:
        return _fallback_research(
            project_name,
            questionnaire_responses,
            analysis_report,
            business_address=business_address,
        )
